\chapter{Error handling}
\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a}{}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a}\index{Error handling@{Error handling}}
\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7803}%
\Hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7803}%


Error handling represents one of the most important considerations when implementing a Node.\+js native add-\/on. When an error occurs in your C++ code you have to handle and dispatch it correctly. {\bfseries{node-\/addon-\/api}} uses return values and Java\+Script exceptions for error handling. You can choose return values or exception handling based on the mechanism that works best for your add-\/on.

The {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}} is a persistent reference (for more info see\+: \doxysectlink{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_25babb8f4ee8ee92c1b4986368972009e}{{\ttfamily Napi\+::Object\+Reference}}{0}) to a Java\+Script error object. Use of this class depends on whether C++ exceptions are enabled at compile time.

If C++ exceptions are enabled (for more info see\+: \doxysectlink{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_266528d00135031cc477eae3ce7dfec6e}{Setup}{0}), then the {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}} class extends {\ttfamily std\+::exception} and enables integrated error-\/handling for C++ exceptions and Java\+Script exceptions.

The following sections explain the approach for each case\+:


\begin{DoxyItemize}
\item Handling Errors With C++ Exceptions
\item Handling Errors Without C++ Exceptions
\end{DoxyItemize}

\label{_exceptions}%


In most cases when an error occurs, the addon should do whatever clean is possible and then return to Java\+Script so that they error can be propagated. In less frequent cases the addon may be able to recover from the error, clear the error and then continue.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7804}{}\doxysection{\texorpdfstring{Handling Errors With C++ Exceptions}{Handling Errors With C++ Exceptions}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7804}
When C++ exceptions are enabled try/catch can be used to catch exceptions thrown from calls to Java\+Script and then they can either be handled or rethrown before returning from a native method.

If a node-\/addon-\/api call fails without executing any Java\+Script code (for example due to an invalid argument), then node-\/addon-\/api automatically converts and throws the error as a C++ exception of type {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}}.

If a Java\+Script function called by C++ code via node-\/addon-\/api throws a Java\+Script exception, then node-\/addon-\/api automatically converts and throws it as a C++ exception of type {\ttfamily \doxylink{namespace_napi}{Napi}\+:Error} on return from the Java\+Script code to the native method.

If a C++ exception of type {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}} escapes from a N-\/\+API C++ callback, then the N-\/\+API wrapper automatically converts and throws it as a Java\+Script exception.

On return from a native method, node-\/addon-\/api will automatically convert a pending C++ exception to a Java\+Script exception.

When C++ exceptions are enabled try/catch can be used to catch exceptions thrown from calls to Java\+Script and then they can either be handled or rethrown before returning from a native method.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7805}{}\doxysection{\texorpdfstring{Examples with C++ exceptions enabled}{Examples with C++ exceptions enabled}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7805}
\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7806}{}\doxysubsection{\texorpdfstring{Throwing a C++ exception}{Throwing a C++ exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7806}

\begin{DoxyCode}{0}
\DoxyCodeLine{Env\ env\ =\ ...}
\DoxyCodeLine{throw\ Napi::Error::New(env,\ \textcolor{stringliteral}{"{}Example\ exception"{}});}
\DoxyCodeLine{\textcolor{comment}{//\ other\ C++\ statements}}
\DoxyCodeLine{\textcolor{comment}{//\ ...}}

\end{DoxyCode}


The statements following the throw statement will not be executed. The exception will bubble up as a C++ exception of type {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}}, until it is either caught while still in C++, or else automatically propagated as a Java\+Script exception when returning to Java\+Script.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7807}{}\doxysubsection{\texorpdfstring{Propagating a N-\/\+API C++ exception}{Propagating a N-\/\+API C++ exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7807}

\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}\ jsFunctionThatThrows\ =\ someObj.\mbox{\hyperlink{class_napi_1_1_value_a9c1a9c4eca9617b0aafbe311c946982a}{As}}<\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}>();}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_value}{Napi::Value}}\ result\ =\ jsFunctionThatThrows(\{\ arg1,\ arg2\ \});}
\DoxyCodeLine{\textcolor{comment}{//\ other\ C++\ statements}}
\DoxyCodeLine{\textcolor{comment}{//\ ...}}

\end{DoxyCode}


The C++ statements following the call to the Java\+Script function will not be executed. The exception will bubble up as a C++ exception of type {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}}, until it is either caught while still in C++, or else automatically propagated as a Java\+Script exception when returning to Java\+Script.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7808}{}\doxysubsection{\texorpdfstring{Handling a N-\/\+API C++ exception}{Handling a N-\/\+API C++ exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7808}

\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}\ jsFunctionThatThrows\ =\ someObj.\mbox{\hyperlink{class_napi_1_1_value_a9c1a9c4eca9617b0aafbe311c946982a}{As}}<\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}>();}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_value}{Napi::Value}}\ result;}
\DoxyCodeLine{\textcolor{keywordflow}{try}\ \{}
\DoxyCodeLine{\ \ \ \ result\ =\ jsFunctionThatThrows(\{\ arg1,\ arg2\ \});}
\DoxyCodeLine{\}\ \textcolor{keywordflow}{catch}\ (\textcolor{keyword}{const}\ Error\&\ e)\ \{}
\DoxyCodeLine{\ \ \ \ cerr\ <<\ \textcolor{stringliteral}{"{}Caught\ JavaScript\ exception:\ "{}}\ +\ e.what();}
\DoxyCodeLine{\}}

\end{DoxyCode}


Since the exception was caught here, it will not be propagated as a Java\+Script exception.

\label{_noexceptions}%
\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7809}{}\doxysection{\texorpdfstring{Handling Errors Without C++ Exceptions}{Handling Errors Without C++ Exceptions}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7809}
If C++ exceptions are disabled (for more info see\+: \doxysectlink{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_266528d00135031cc477eae3ce7dfec6e}{Setup}{0}), then the {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}} class does not extend {\ttfamily std\+::exception}. This means that any calls to node-\/addon-\/api function do not throw a C++ exceptions. Instead, it raises {\itshape pending} Java\+Script exceptions and returns an {\itshape empty} {\ttfamily \doxylink{class_napi_1_1_value}{Napi\+::\+Value}}. The calling code should check {\ttfamily env.\+Is\+Exception\+Pending()} before attempting to use a returned value, and may use methods on the {\ttfamily \doxylink{class_napi_1_1_env}{Napi\+::\+Env}} class to check for, get, and clear a pending Java\+Script exception (for more info see\+: \doxysectlink{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_29e67c9204cf2be24debd79122b6a3af1}{Env}{0}). If the pending exception is not cleared, it will be thrown when the native code returns to Java\+Script.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7810}{}\doxysection{\texorpdfstring{Examples with C++ exceptions disabled}{Examples with C++ exceptions disabled}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7810}
\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7811}{}\doxysubsection{\texorpdfstring{Throwing a JS exception}{Throwing a JS exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7811}

\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_env}{Napi::Env}}\ env\ =\ ...}
\DoxyCodeLine{Napi::Error::New(env,\ \textcolor{stringliteral}{"{}Example\ exception"{}}).ThrowAsJavaScriptException();}
\DoxyCodeLine{\textcolor{keywordflow}{return};}

\end{DoxyCode}


After throwing a Java\+Script exception, the code should generally return immediately from the native callback, after performing any necessary cleanup.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7812}{}\doxysubsection{\texorpdfstring{Propagating a N-\/\+API JS exception}{Propagating a N-\/\+API JS exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7812}

\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_env}{Napi::Env}}\ env\ =\ ...}
\DoxyCodeLine{Napi::Function\ jsFunctionThatThrows\ =\ someObj.\mbox{\hyperlink{class_napi_1_1_value_a9c1a9c4eca9617b0aafbe311c946982a}{As}}<\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}>();}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_value}{Napi::Value}}\ result\ =\ jsFunctionThatThrows(\{\ arg1,\ arg2\ \});}
\DoxyCodeLine{\textcolor{keywordflow}{if}\ (env.IsExceptionPending())\ \{}
\DoxyCodeLine{\ \ \ \ Error\ e\ =\ env.GetAndClearPendingException();}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{return}\ e.Value();}
\DoxyCodeLine{\}}

\end{DoxyCode}


If env.\+Is\+Exception\+Pending() returns true a Java\+Script exception is pending. To let the exception propagate, the code should generally return immediately from the native callback, after performing any necessary cleanup.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7813}{}\doxysubsection{\texorpdfstring{Handling a N-\/\+API JS exception}{Handling a N-\/\+API JS exception}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7813}

\begin{DoxyCode}{0}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_env}{Napi::Env}}\ env\ =\ ...}
\DoxyCodeLine{Napi::Function\ jsFunctionThatThrows\ =\ someObj.\mbox{\hyperlink{class_napi_1_1_value_a9c1a9c4eca9617b0aafbe311c946982a}{As}}<\mbox{\hyperlink{class_napi_1_1_function}{Napi::Function}}>();}
\DoxyCodeLine{\mbox{\hyperlink{class_napi_1_1_value}{Napi::Value}}\ result\ =\ jsFunctionThatThrows(\{\ arg1,\ arg2\ \});}
\DoxyCodeLine{\textcolor{keywordflow}{if}\ (env.IsExceptionPending())\ \{}
\DoxyCodeLine{\ \ \ \ \mbox{\hyperlink{class_napi_1_1_error}{Napi::Error}}\ e\ =\ env.GetAndClearPendingException();}
\DoxyCodeLine{\ \ \ \ cerr\ <<\ \textcolor{stringliteral}{"{}Caught\ JavaScript\ exception:\ "{}}\ +\ e.Message();}
\DoxyCodeLine{\}}

\end{DoxyCode}


Since the exception was cleared here, it will not be propagated as a Java\+Script exception after the native callback returns.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7814}{}\doxysection{\texorpdfstring{Calling N-\/\+API directly from a {\bfseries{node-\/addon-\/api}} addon}{Calling N-\/\+API directly from a {\bfseries{node-\/addon-\/api}} addon}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7814}
{\bfseries{node-\/addon-\/api}} provides macros for throwing errors in response to non-\/\+OK {\ttfamily napi\+\_\+status} results when calling \href{https://nodejs.org/docs/latest/api/n-api.html}{\texttt{ N-\/\+API}} functions from within a native addon. These macros are defined differently depending on whether C++ exceptions are enabled or not, but are available for use in either case.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7815}{}\doxysubsection{\texorpdfstring{{\ttfamily NAPI\+\_\+\+THROW(e, ...)}}{{\ttfamily NAPI\+\_\+\+THROW(e, ...)}}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7815}
This macro accepts a {\ttfamily \doxylink{class_napi_1_1_error}{Napi\+::\+Error}}, throws it, and returns the value given as the last parameter. If C++ exceptions are enabled (by defining {\ttfamily NAPI\+\_\+\+CPP\+\_\+\+EXCEPTIONS} during the build), the return value will be ignored.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7816}{}\doxysubsection{\texorpdfstring{{\ttfamily NAPI\+\_\+\+THROW\+\_\+\+IF\+\_\+\+FAILED(env, status, ...)}}{{\ttfamily NAPI\+\_\+\+THROW\+\_\+\+IF\+\_\+\+FAILED(env, status, ...)}}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7816}
This macro accepts a {\ttfamily \doxylink{class_napi_1_1_env}{Napi\+::\+Env}} and a {\ttfamily napi\+\_\+status}. It constructs an error from the {\ttfamily napi\+\_\+status}, throws it, and returns the value given as the last parameter. If C++ exceptions are enabled (by defining {\ttfamily NAPI\+\_\+\+CPP\+\_\+\+EXCEPTIONS} during the build), the return value will be ignored.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7817}{}\doxysubsection{\texorpdfstring{{\ttfamily NAPI\+\_\+\+THROW\+\_\+\+IF\+\_\+\+FAILED\+\_\+\+VOID(env, status)}}{{\ttfamily NAPI\+\_\+\+THROW\+\_\+\+IF\+\_\+\+FAILED\+\_\+\+VOID(env, status)}}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7817}
This macro accepts a {\ttfamily \doxylink{class_napi_1_1_env}{Napi\+::\+Env}} and a {\ttfamily napi\+\_\+status}. It constructs an error from the {\ttfamily napi\+\_\+status}, throws it, and returns.\hypertarget{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7818}{}\doxysubsection{\texorpdfstring{{\ttfamily NAPI\+\_\+\+FATAL\+\_\+\+IF\+\_\+\+FAILED(status, location, message)}}{{\ttfamily NAPI\+\_\+\+FATAL\+\_\+\+IF\+\_\+\+FAILED(status, location, message)}}}\label{md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_2203d072898c38e99e77857f01173178a_autotoc_md7818}
This macro accepts a {\ttfamily napi\+\_\+status}, a C string indicating the location where the error occurred, and a second C string for the message to display. 